name : NetCore-BooksRestAPI-CI
trigger:
  branches:
    include:
      - master
  paths:
    include:
      - BooksRestAPI/*
 
pool:
  vmImage: 'ubuntu-latest'
 
variables:
  buildConfiguration: 'Release'
 
steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/BooksRestAPI*.csproj'
  displayName: 'Restore Nuget Packages'
 
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/BooksRestAPI*.csproj'
    arguments: '--no-restore'
  displayName: 'Build projects'
 
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/BooksRestAPITest.csproj'
    arguments: '--no-restore --no-build'
  displayName: 'Run Tests'
 
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/BooksRestAPI.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
    modifyOutputPath: false
  displayName: 'Publish BooksRestAPI'
  condition: and(succeeded(), ne(variables['Build.Reason'],'PullRequest'))
  

    
    
  
    
